# Generated by Django 5.1.4 on 2025-01-23 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0005_event_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=100)),
                ('blog_date', models.DateField(auto_now_add=True)),
                ('blog_content', models.TextField(max_length=3000)),
                ('blog_image', models.ImageField(blank=True, null=True, upload_to='blog_images/')),
            ],
        ),
    ]
